#!/usr/bin/python3

from math import *
import sys
import os

def to_int(arg):
    try:
        return int(arg)
    except ValueError:
        exit(84)

def error_case():
    if len(sys.argv) != 2:
        exit(84)
    if (to_int(sys.argv[1]) < 0):
        exit(84)
    if (sys.argv[1] == "-h"):
        print("USAGE\n\t./110borwein n\n")
        print("DESCRIPTION")
        print("\tn\tconstant defining the integral to be computed")
        exit(0)

def factorial(nb):
    var = 1
    for i in range(2, nb + 1):
        var *= i
    return (var)

def calcul(n, x):
    if x == 0:
        return 1
    result = (sin(x) / x)
    j = 3
    for i in range(n):
        result *= sin(x / j) / (x / j)
        j += 2
    return result

def frange(start, end=None, inc=None):
    if end == None:
        end = start + 0.0
        start = 0.0
    if inc == None:
        inc = 1.0
    L = []
    while 1:
        next = start + len(L) * inc
        if inc > 0 and next >= end:
            break
        elif inc < 0 and next <= end:
            break
        L.append(next)
    return L

def midpoint(n):
    result = 0.00
    for i in frange(0, 5000, 0.5):
        var = (i + (i + 0.5)) / 2
        func = calcul(n, var)
        result += func * 0.5
    print("Midpoint:")
    print("I%d = %.10f" %(n, result))
    print("diff = %.10f" %(abs(result - pi/2)))

def trapezoids(n):
    result = 0.00
    for i in frange(0, 5000, 0.5):
        var = (calcul(n, i) + calcul(n, i + 0.5)) / 2
        result += var * 0.5
    print("\nTrapezoidal:")
    print("I%d = %.10f" %(n, result))
    print("diff = %.10f" %(abs(result - pi/2)))

def simpson(n):
    result = 0.00
    for i in frange(0, 5000, 0.5):
        var = (i + (i + 0.5)) / 2
        func = calcul(n, var)
        function = ((calcul(n, i) + calcul(n, i + 0.5)) + (4 * func)) / 6
        result += function * 0.5
    print("\nSimpson:")
    print("I%d = %.10f" %(n, result))
    print("diff = %.10f" %(abs(result - pi/2)))

def main():
    error_case()
    n = to_int(sys.argv[1])
    midpoint(n)
    trapezoids(n)
    simpson(n)

main()